image: docker:stable

services:
  - docker:stable-dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  BUILD_DIR: build/

before_script:
  # registry login
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - echo $APPID
      && echo $MOD
      && echo $FIX_APPMANIFEST
      && echo $GAME
      && echo $VERSION

    # $APPID, $MOD, $FIX_APPMANIFEST, $GAME, $VERSION to be issued as variables through pipeline trigger
    - docker build
      --build-arg APPID=$APPID
      --build-arg MOD=$MOD
      --build-arg FIX_APPMANIFEST=$FIX_APPMANIFEST
      --build-arg GAME=$GAME
      --build-arg VERSION=$VERSION
      -t "${REGISTRY_USER}/${GAME}:latest"
      -t "${REGISTRY_USER}/${GAME}:${VERSION}"
      -t "${CI_REGISTRY_IMAGE}/${GAME}:latest"
      -t "${CI_REGISTRY_IMAGE}/${GAME}:${VERSION}"
      -t "${CI_REGISTRY_IMAGE}/${GAME}:${CI_JOB_ID}"
      $BUILD_DIR

    - docker push "${REGISTRY_USER}/${GAME}"
    - docker push "${CI_REGISTRY_IMAGE}/${GAME}"
  only:
    - triggers

after_script:
  - docker logout
  - docker logout $CI_REGISTRY