language: bash
services: docker

env:
  global:
    - BUILD_DIR="build/"
    - UPDATE_DIR="update/"

before_script:
  - whoami
  - cat /etc/*release
  - df -h
  - free

  - if [ "${APPID}" = 90 ]; then
      REPOSITORY="${REGISTRY_GOLDSOURCE}/${GAME}";
    else
      REPOSITORY="${REGISTRY_SOURCE}/${GAME}";
    fi

  # Terminate the travis build on any error
  - set -e

  - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

script:
  - date

  # Build / Update the game image
  - if [ "${STAGE}" = 'build' ]; then
      docker build
        --build-arg APPID="${APPID}"
        --build-arg MOD="${MOD}"
        --build-arg FIX_APPMANIFEST="${FIX_APPMANIFEST}"
        -t "${REPOSITORY}:${GAME_VERSION}"
        --label "appid=${APPID}"
        --label "mod=${MOD}"
        --label "game=${GAME}"
        --label "game_version=${GAME_VERSION}"
        --label "game_update_count=0"
        "${BUILD_DIR}";
      docker inspect "${REPOSITORY}:${GAME_VERSION}" -f '{{.Config.Labels}}';
      if [ "${LATEST}" = true ]; then
        docker tag "${REPOSITORY}:${GAME_VERSION}" "${REPOSITORY}:latest";
      fi;
    elif [ "${STAGE}" = 'update' ]; then
      docker build
        --build-arg GAME_IMAGE="${REPOSITORY}:latest"
        -t "${REPOSITORY}:latest"
        --label "game_version=${GAME_VERSION}"
        --label "game_update_count=${GAME_UPDATE_COUNT}"
        "${UPDATE_DIR}";
      docker inspect "${REPOSITORY}:latest" -f '{{.Config.Labels}}';
    fi
  - docker images

  # Test the game image
  - if [ ! "${NO_TEST}" = true ]; then
      if [ "${APPID}" = 90 ]; then
        GAME_BIN="hlds_linux";
      else
        GAME_BIN="srcds_linux";
      fi;
      if [ "${STAGE}" = 'build' ]; then
        TEST_IMAGE="${REPOSITORY}:${GAME_VERSION}";
      elif [ "${STAGE}" = 'update' ]; then
        TEST_IMAGE="${REPOSITORY}:latest";
      fi;
      docker run -t --rm "${TEST_IMAGE}" "printenv && ls -al && exec ${GAME_BIN} -game ${GAME} +version +exit";
    fi
  - date

  # Push the image
  - if [ ! "${NO_PUSH}" = true ]; then
      travis_wait 30 docker push "${REPOSITORY}";
      date;
    fi

after_script:
  - docker logout
  - set +e